# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pricechangedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='TotalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
