# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180326_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AnyOtherFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='AssetTagPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='BasePriceperUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='DeliveryChargeperunit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='FreightCharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='MarkupPriceperUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='RecycleFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='WarrantyPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
