# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductAVEng', '0001_initial'),
        ('ProductAccessory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate',
            fields=[
            ],
            options={
                'verbose_name': 'Duplicate_Hardware',
                'proxy': True,
                'indexes': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='DuplicateAccessory',
            fields=[
            ],
            options={
                'verbose_name': 'Duplicate_Accessory',
                'proxy': True,
                'indexes': [],
            },
            bases=('ProductAccessory.productaccessory',),
        ),
        migrations.CreateModel(
            name='DuplicateAVEng',
            fields=[
            ],
            options={
                'verbose_name': 'Duplicate_AVEng',
                'proxy': True,
                'indexes': [],
            },
            bases=('ProductAVEng.productaveng',),
        ),
    ]
