# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:16
from __future__ import unicode_literals

import ProductAVEng.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAVEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthofEntry', models.CharField(blank=True, max_length=100, null=True)),
                ('DateofEntry', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ProductName', models.CharField(default='', max_length=200)),
                ('ProductCategory', models.CharField(default='', max_length=50)),
                ('ProductType', models.CharField(blank=True, max_length=100, null=True)),
                ('Specifications', models.TextField(blank=True, null=True)),
                ('Warranty', models.NullBooleanField()),
                ('WarrantyPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to=ProductAVEng.models.upload_image_path)),
                ('Supplier', models.CharField(default='', max_length=100)),
                ('StockAvailable', models.IntegerField(blank=True, null=True)),
                ('SupplierType', models.CharField(max_length=100)),
                ('Partnumber', models.CharField(default='', max_length=100)),
                ('UPC', models.CharField(blank=True, max_length=100, null=True)),
                ('SKU', models.CharField(blank=True, max_length=100, null=True)),
                ('Region', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('QuoteValidity', models.IntegerField(default=0)),
                ('UnitofMeasure', models.CharField(max_length=100)),
                ('Currency', models.CharField(default='', max_length=100)),
                ('TotalPrice', models.FloatField(default=0.0)),
                ('BasePriceperUnit', models.FloatField(default=0.0)),
                ('MarkupPriceperUnit', models.FloatField(default=0.0)),
                ('DeliveryChargeperunit', models.FloatField(default=0.0)),
                ('WarrantyPrice', models.FloatField(default=0.0)),
                ('AssetTagPrice', models.FloatField(default=0.0)),
                ('Taxes', models.FloatField(default=0.0)),
                ('RecycleFee', models.FloatField(default=0.0)),
                ('FreightCharge', models.FloatField(default=0.0)),
                ('AnyOtherFee', models.FloatField(default=0.0)),
                ('StockLeadTime', models.IntegerField(default='')),
                ('DeliveryLeadTime', models.IntegerField(default='')),
                ('PriceChange', models.NullBooleanField()),
                ('PriceApproved', models.NullBooleanField()),
                ('PriceApprovalDate', models.DateField(blank=True, null=True)),
                ('GoogleApproverNameAvailable', models.NullBooleanField()),
                ('GoogleApprover', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ReasonForPriceChange', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('EoLStatus', models.NullBooleanField()),
                ('EoLDate', models.DateField(blank=True, null=True)),
                ('PreviousMPN', models.CharField(blank=True, max_length=100, null=True)),
                ('PreviousPartNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('SplInstructions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Data Upload for AV Eng',
            },
        ),
    ]
