# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'ordering': ('ProductName', 'ProductCategory'),
                'proxy': True,
                'indexes': [],
            },
            bases=('products.product',),
        ),
    ]
